45 auth session flow
bookmebus/vshop168app pull request #50
Opened 2020-12-05 07:34 UTC by theacheng

2020-12-06 00:43 UTC, bookmebus requested changes

2020-12-06 00:43 UTC, bookmebus commented on lib/services/validators/password_validator.dart
> +class PasswordValidator extends BaseValidator {
Most languages provide a strong password check lib. there are more complicated than this like entropy level. No need to have this one but use a third party instead

2020-12-06 00:43 UTC, bookmebus commented on test/services/validators/email_validator_test.dart
> +    test("return true if email is valid", () {
add another test for failure case

2020-12-06 00:43 UTC, bookmebus commented on test/services/validators/phone_number_validator_test.dart
> +    test("return true if phone number is valid!", () async {
add another test for failure case

2020-12-06 00:43 UTC, bookmebus commented on test/services/validators/username_validator_test.dart
> +    test("return true if username is not contain special char and start from 0", () {
add another test for failure

2020-12-08 08:04 UTC, theacheng commented
Now at 3 PM pull request, I almost did it at 1 PM, then I face with a problem that I tried to search on google and found this: 
```
git clean -xfd
git stash save --keep-index
git stash drop
git pull
flutter doctor
```
This just clears all my changes and also file on git ignore even api_constrant.dart that I have to rewrite it.

2020-12-08 09:41 UTC, theacheng commented on lib/screens/authentication/components/social_sign_in.dart
>  import 'package:flutter/material.dart';
Can't rename the file to social_signin.dart, when I saved it, it automatically renames to social_signIn.dart

2020-12-14 06:53 UTC, merged